language: c
dist: xenial
env:
  - LIBWEBSOCKETS_VERSION=system
  - LIBWEBSOCKETS_VERSION=2.0.3
  - LIBWEBSOCKETS_VERSION=2.1.1
  - LIBWEBSOCKETS_VERSION=2.2.2
  - LIBWEBSOCKETS_VERSION=2.3.0
  - LIBWEBSOCKETS_VERSION=2.4.2
  - LIBWEBSOCKETS_VERSION=3.0.0
branches:
  only:
    - master
addons:
  apt:
    packages:
      - cmake
      - libjson-c-dev
      - libssl-dev
      - libuv-dev
install: |
  if [ "$LIBWEBSOCKETS_VERSION" == "system" ]; then
    sudo apt-get install -y libwebsockets-dev
  else
    echo "Compiling libwebsockets-$LIBWEBSOCKETS_VERSION from source..."
    pushd /tmp
      curl -sLo- https://github.com/warmcat/libwebsockets/archive/v$LIBWEBSOCKETS_VERSION.tar.gz | tar xz
      cd libwebsockets-$LIBWEBSOCKETS_VERSION
      cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=/usr -DLWS_WITHOUT_TESTAPPS=ON -DLWS_UNIX_SOCK=ON -DLWS_WITH_LIBUV=ON .
      make && sudo make install
    popd
  fi
script:
  - cmake -DCMAKE_BUILD_TYPE=RELEASE .
  - make && sudo make install
  - ttyd -v
